"""create core tables with timestamptz

Revision ID: 555c1c687cc6
Revises:
Create Date: 2026-05-08 07:49:13.437037
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "555c1c687cc6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "augments",
        sa.Column("augment_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tier", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("icon", sa.String(length=200), nullable=True),
        sa.Column("tft_set_number", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("augment_id", name=op.f("augments_pkey")),
    )
    op.create_index("idx_augment_tier", "augments", ["tier"], unique=False)
    op.create_table(
        "champions",
        sa.Column("unit_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("cost", sa.SmallInteger(), nullable=False),
        sa.Column("traits", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("ability_name", sa.String(length=100), nullable=True),
        sa.Column("ability_desc", sa.Text(), nullable=True),
        sa.Column(
            "stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("tft_set_number", sa.Integer(), nullable=False),
        sa.Column("patch_added", sa.String(length=10), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("unit_id", name=op.f("champions_pkey")),
    )
    op.create_index("idx_champion_cost", "champions", ["cost"], unique=False)
    op.create_table(
        "items",
        sa.Column("item_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=200), nullable=True),
        sa.Column("is_component", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_craftable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_embleme", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_spatula", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("composition", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("tft_set_number", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("item_id", name=op.f("items_pkey")),
    )
    op.create_table(
        "matches",
        sa.Column("match_id", sa.String(length=30), nullable=False),
        sa.Column("patch", sa.String(length=10), nullable=False),
        sa.Column("patch_major", sa.SmallInteger(), nullable=False),
        sa.Column("patch_minor", sa.SmallInteger(), nullable=False),
        sa.Column("game_datetime", sa.DateTime(), nullable=False),
        sa.Column("game_length", sa.Integer(), nullable=False),
        sa.Column("game_variation", sa.String(length=50), nullable=True),
        sa.Column("queue_id", sa.Integer(), nullable=True),
        sa.Column("tft_set_number", sa.Integer(), nullable=True),
        sa.Column("tft_set_core_name", sa.String(length=50), nullable=True),
        sa.Column("region", sa.String(length=10), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("matches_pkey")),
        sa.UniqueConstraint("match_id", name=op.f("matches_match_id_key")),
    )
    op.create_index("idx_matches_game_datetime", "matches", ["game_datetime"], unique=False)
    op.create_index("idx_matches_patch", "matches", ["patch"], unique=False)
    op.create_index(
        "idx_matches_patch_datetime", "matches", ["patch", "game_datetime"], unique=False
    )
    op.create_table(
        "players",
        sa.Column("puuid", sa.String(length=78), nullable=False),
        sa.Column("game_name", sa.String(length=50), nullable=False),
        sa.Column("tag_line", sa.String(length=10), nullable=False),
        sa.Column("region", sa.String(length=10), server_default="vn2", nullable=False),
        sa.Column("summoner_id", sa.String(length=100), nullable=True),
        sa.Column("account_id", sa.String(length=100), nullable=True),
        sa.Column("profile_icon_id", sa.Integer(), nullable=True),
        sa.Column("summoner_level", sa.Integer(), nullable=True),
        sa.Column("last_fetched_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("players_pkey")),
        sa.UniqueConstraint("puuid", name=op.f("players_puuid_key")),
    )
    op.create_index("idx_players_game_name_tag", "players", ["game_name", "tag_line"], unique=False)
    op.create_table(
        "traits",
        sa.Column("trait_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tft_set_number", sa.Integer(), nullable=False),
        sa.Column(
            "breakpoints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("trait_id", name=op.f("traits_pkey")),
    )
    op.create_index("idx_trait_set", "traits", ["tft_set_number"], unique=False)
    op.create_table(
        "augment_stats",
        sa.Column("augment_id", sa.String(length=100), nullable=False),
        sa.Column("tft_set_number", sa.Integer(), nullable=False),
        sa.Column("patch", sa.String(length=10), nullable=False),
        sa.Column("queue_type", sa.String(length=20), server_default="ranked", nullable=False),
        sa.Column("stage", sa.String(length=10), server_default="_all", nullable=False),
        sa.Column("calculated_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.Column("games_played", sa.Integer(), server_default="0", nullable=False),
        sa.Column("win_rate", sa.Numeric(), nullable=True),
        sa.Column("top4_rate", sa.Numeric(), nullable=True),
        sa.Column("avg_placement", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(
            ["augment_id"], ["augments.augment_id"], name=op.f("augment_stats_augment_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "augment_id",
            "tft_set_number",
            "patch",
            "queue_type",
            "stage",
            "calculated_at",
            name=op.f("augment_stats_pkey"),
        ),
    )
    op.create_index(
        "idx_as_augment_patch", "augment_stats", ["augment_id", "patch", "queue_type"], unique=False
    )
    op.create_table(
        "champion_stats",
        sa.Column("champion_id", sa.String(length=100), nullable=False),
        sa.Column("tft_set_number", sa.Integer(), nullable=False),
        sa.Column("patch", sa.String(length=10), nullable=False),
        sa.Column("queue_type", sa.String(length=20), server_default="ranked", nullable=False),
        sa.Column("calculated_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.Column("games_played", sa.Integer(), server_default="0", nullable=False),
        sa.Column("wins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("top4s", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_placement", sa.Numeric(), server_default="0", nullable=False),
        sa.Column("win_rate", sa.Numeric(), nullable=True),
        sa.Column("top4_rate", sa.Numeric(), nullable=True),
        sa.Column("avg_placement", sa.Numeric(), nullable=True),
        sa.Column("pick_rate", sa.Numeric(), nullable=True),
        sa.Column("tier_score", sa.Numeric(), nullable=True),
        sa.Column("tier", sa.String(length=1), nullable=True),
        sa.ForeignKeyConstraint(
            ["champion_id"], ["champions.unit_id"], name=op.f("champion_stats_champion_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "champion_id",
            "tft_set_number",
            "patch",
            "queue_type",
            "calculated_at",
            name=op.f("champion_stats_pkey"),
        ),
    )
    op.create_index(
        "idx_cs_champion_patch",
        "champion_stats",
        ["champion_id", "patch", "queue_type"],
        unique=False,
    )
    op.create_index("idx_cs_tier_score", "champion_stats", ["patch", "tier_score"], unique=False)
    op.create_table(
        "item_stats",
        sa.Column("item_id", sa.String(length=100), nullable=False),
        sa.Column("champion_id", sa.String(length=100), server_default="_overall", nullable=False),
        sa.Column("tft_set_number", sa.Integer(), nullable=False),
        sa.Column("patch", sa.String(length=10), nullable=False),
        sa.Column("queue_type", sa.String(length=20), server_default="ranked", nullable=False),
        sa.Column("calculated_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.Column("games_played", sa.Integer(), server_default="0", nullable=False),
        sa.Column("win_rate", sa.Numeric(), nullable=True),
        sa.Column("top4_rate", sa.Numeric(), nullable=True),
        sa.Column("avg_placement", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.item_id"], name=op.f("item_stats_item_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "item_id",
            "champion_id",
            "tft_set_number",
            "patch",
            "queue_type",
            "calculated_at",
            name=op.f("item_stats_pkey"),
        ),
    )
    op.create_table(
        "match_participants",
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("puuid", sa.String(length=78), nullable=False),
        sa.Column("placement", sa.SmallInteger(), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("gold_left", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("last_round", sa.SmallInteger(), nullable=True),
        sa.Column("players_eliminated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_damage_to_players", sa.Integer(), server_default="0", nullable=False),
        sa.Column("augments", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "traits_active",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("time_eliminated", sa.Numeric(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "placement BETWEEN 1 AND 8", name=op.f("match_participants_ck_placement_range_check")
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("match_participants_match_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("match_participants_pkey")),
    )
    op.create_index("idx_mp_match_id", "match_participants", ["match_id"], unique=False)
    op.create_index("idx_mp_match_puuid", "match_participants", ["match_id", "puuid"], unique=False)
    op.create_index("idx_mp_placement", "match_participants", ["placement"], unique=False)
    op.create_index("idx_mp_puuid", "match_participants", ["puuid"], unique=False)
    op.create_table(
        "trait_stats",
        sa.Column("trait_id", sa.String(length=100), nullable=False),
        sa.Column("active_tier", sa.SmallInteger(), nullable=False),
        sa.Column("tft_set_number", sa.Integer(), nullable=False),
        sa.Column("patch", sa.String(length=10), nullable=False),
        sa.Column("queue_type", sa.String(length=20), server_default="ranked", nullable=False),
        sa.Column("calculated_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.Column("games_played", sa.Integer(), server_default="0", nullable=False),
        sa.Column("wins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("top4s", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_placement", sa.Numeric(), server_default="0", nullable=False),
        sa.Column("win_rate", sa.Numeric(), nullable=True),
        sa.Column("top4_rate", sa.Numeric(), nullable=True),
        sa.Column("avg_placement", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trait_id"], ["traits.trait_id"], name=op.f("trait_stats_trait_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "trait_id",
            "active_tier",
            "tft_set_number",
            "patch",
            "queue_type",
            "calculated_at",
            name=op.f("trait_stats_pkey"),
        ),
    )
    op.create_index(
        "idx_ts_trait_patch", "trait_stats", ["trait_id", "patch", "queue_type"], unique=False
    )
    op.create_table(
        "participant_units",
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.String(length=100), nullable=False),
        sa.Column("tier", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("rarity", sa.SmallInteger(), nullable=True),
        sa.Column("items", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["match_participants.id"],
            name=op.f("participant_units_participant_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("participant_units_pkey")),
    )
    op.create_index("idx_pu_participant_id", "participant_units", ["participant_id"], unique=False)
    op.create_index("idx_pu_unit_id", "participant_units", ["unit_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_pu_unit_id", table_name="participant_units")
    op.drop_index("idx_pu_participant_id", table_name="participant_units")
    op.drop_table("participant_units")
    op.drop_index("idx_ts_trait_patch", table_name="trait_stats")
    op.drop_table("trait_stats")
    op.drop_index("idx_mp_puuid", table_name="match_participants")
    op.drop_index("idx_mp_placement", table_name="match_participants")
    op.drop_index("idx_mp_match_puuid", table_name="match_participants")
    op.drop_index("idx_mp_match_id", table_name="match_participants")
    op.drop_table("match_participants")
    op.drop_table("item_stats")
    op.drop_index("idx_cs_tier_score", table_name="champion_stats")
    op.drop_index("idx_cs_champion_patch", table_name="champion_stats")
    op.drop_table("champion_stats")
    op.drop_index("idx_as_augment_patch", table_name="augment_stats")
    op.drop_table("augment_stats")
    op.drop_index("idx_trait_set", table_name="traits")
    op.drop_table("traits")
    op.drop_index("idx_players_game_name_tag", table_name="players")
    op.drop_table("players")
    op.drop_index("idx_matches_patch_datetime", table_name="matches")
    op.drop_index("idx_matches_patch", table_name="matches")
    op.drop_index("idx_matches_game_datetime", table_name="matches")
    op.drop_table("matches")
    op.drop_table("items")
    op.drop_index("idx_champion_cost", table_name="champions")
    op.drop_table("champions")
    op.drop_index("idx_augment_tier", table_name="augments")
    op.drop_table("augments")
    # ### end Alembic commands ###
